/**
 * 文本提取与清洗器 - 将原始文本转换为结构化 Markdown
 * 智能内容压缩：优先保留简历核心内容
 * 迁移时可直接复用
 */

// 简历常见章节标题（用于结构化识别）
const SECTION_HEADERS = [
  '基本信息', '个人简介', '个人信息', '基础信息', '联系方式',
  '教育背景', '教育经历', '学历',
  '工作经历', '工作经验', '职业经历', '工作履历',
  '项目经历', '项目经验',
  '实习经历', '实习经验',
  '校园经历', '校园活动', '社团经历', '学生组织',
  '科研经历', '研究经历', '学术经历',
  '专业技能', '技能特长', '技术能力', '技术栈', '技能',
  '证书', '资格证书', '荣誉', '获奖', '证书荣誉', '荣誉奖项',
  '自我评价', '个人优势', '个人评价', '自我总结', '个人总结',
  '求职意向', '期望岗位', '目标岗位',
] as const;

// 章节优先级（数字越小优先级越高）
const SECTION_PRIORITY: Record<string, number> = {
  '基本信息': 1, '个人信息': 1, '基础信息': 1, '联系方式': 1,
  '教育背景': 2, '教育经历': 2, '学历': 2,
  '工作经历': 3, '工作经验': 3, '职业经历': 3,
  '项目经历': 4, '项目经验': 4,
  '实习经历': 5, '实习经验': 5,
  '科研经历': 6, '研究经历': 6,
  '校园经历': 7, '校园活动': 7, '社团经历': 7,
  '专业技能': 8, '技能特长': 8, '技术能力': 8, '技术栈': 8, '技能': 8,
  '证书': 9, '资格证书': 9, '荣誉': 9, '获奖': 9, '证书荣誉': 9,
  '自我评价': 10, '个人优势': 10, '个人评价': 10, '自我总结': 10,
  '求职意向': 11, '期望岗位': 11, '目标岗位': 11,
};

// 噪音模式（需要清除的内容）
const NOISE_PATTERNS = [
  /^[\s]*第?\s*\d+\s*页[\s/共]*\d*[\s]*$/, // 页码
  /^[\s]*Page\s*\d+[\s/of]*\d*[\s]*$/i, // 英文页码
  /^[\s]*-\s*\d+\s*-[\s]*$/, // 分隔符页码
  /^[\s]*\d+\s*\/\s*\d+[\s]*$/, // 数字/数字 格式页码
  /^[\s]*Created with.*$/i, // 工具水印
  /^[\s]*Generated by.*$/i, // 生成工具标记
  /^[\s]*Powered by.*$/i, // 工具标记
  /^[\s]*www\..*$/i, // 网址行
  /^[\s]*http[s]?:\/\/.*$/i, // URL行（但保留邮箱中的@）
  /^[\s]*[\-=_~*]{5,}[\s]*$/, // 分隔线
  /^[\s]*\d+[\s]*$/, // 纯数字行（可能是页码）
] as const;

// 重复内容检测模式
const DUPLICATE_INDICATORS = [
  /^[\s]*[\-•·]\s*$/, // 空列表项
  /^[\s]*[\u4e00-\u9fa5]\s*$/, // 单字行（可能是排版错误）
];

/**
 * 清洗原始文本，去除噪音
 */
export function cleanText(rawText: string): string {
  const lines = rawText.split('\n');
  const cleanedLines: string[] = [];
  let prevEmpty = false;
  const seenLines = new Set<string>(); // 去重

  for (const line of lines) {
    const trimmed = line.trim();

    // 跳过空行（连续空行只保留一个）
    if (trimmed === '') {
      if (!prevEmpty) {
        cleanedLines.push('');
        prevEmpty = true;
      }
      continue;
    }
    prevEmpty = false;

    // 跳过噪音行
    let isNoise = false;
    for (const pattern of NOISE_PATTERNS) {
      if (pattern.test(trimmed)) {
        isNoise = true;
        break;
      }
    }
    if (isNoise) continue;

    // 跳过重复行（完全相同的内容只保留一次）
    if (seenLines.has(trimmed) && trimmed.length > 10) {
      continue;
    }
    seenLines.add(trimmed);

    // 跳过无意义行
    let isDuplicate = false;
    for (const pattern of DUPLICATE_INDICATORS) {
      if (pattern.test(trimmed)) {
        isDuplicate = true;
        break;
      }
    }
    if (isDuplicate) continue;

    cleanedLines.push(trimmed);
  }

  return cleanedLines.join('\n').trim();
}

/**
 * 将清洗后的文本转换为结构化 Markdown
 */
export function structureToMarkdown(cleanedText: string): string {
  const lines = cleanedText.split('\n');
  const result: string[] = [];
  let currentSection = '';

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      result.push('');
      continue;
    }

    // 检查是否是章节标题
    let isSection = false;
    for (const header of SECTION_HEADERS) {
      if (trimmed === header || trimmed.startsWith(header + '：') || trimmed.startsWith(header + ':')) {
        // 添加章节标题
        result.push('');
        result.push(`## ${header}`);
        result.push('');
        currentSection = header;
        isSection = true;

        // 如果标题后面有内容（如"基本信息：张三"），提取内容
        const afterColon = trimmed.slice(header.length + 1).trim();
        if (afterColon) {
          result.push(afterColon);
        }
        break;
      }
    }

    if (!isSection) {
      result.push(trimmed);
    }
  }

  return result.join('\n').trim();
}

/**
 * 完整文本处理流程：原始文本 → 清洗 → 结构化
 */
export function extractAndStructure(rawText: string): string {
  const cleaned = cleanText(rawText);
  const structured = structureToMarkdown(cleaned);
  return structured;
}

/**
 * 智能内容压缩 - 优先保留简历核心内容
 * 按章节优先级分配配额，确保重要内容不被截断
 */
export function smartCompress(text: string, maxLength: number = 8000): string {
  if (text.length <= maxLength) return text;

  // 按章节分割内容
  const sections = splitBySections(text);
  
  // 按优先级排序
  sections.sort((a, b) => {
    const priorityA = SECTION_PRIORITY[a.title] ?? 99;
    const priorityB = SECTION_PRIORITY[b.title] ?? 99;
    return priorityA - priorityB;
  });

  // 分配配额
  const result: string[] = [];
  let remaining = maxLength;
  
  // 高优先级章节（基本信息、教育、工作、项目）至少保留80%内容
  const highPrioritySections = sections.filter(s => (SECTION_PRIORITY[s.title] ?? 99) <= 5);
  const otherSections = sections.filter(s => (SECTION_PRIORITY[s.title] ?? 99) > 5);

  // 先处理高优先级章节
  for (const section of highPrioritySections) {
    const sectionText = section.fullText;
    if (sectionText.length <= remaining) {
      result.push(sectionText);
      remaining -= sectionText.length;
    } else {
      // 截断但保留开头（通常是关键信息）
      const truncated = sectionText.slice(0, Math.max(200, remaining - 50));
      result.push(truncated + '\n[...内容已精简]');
      remaining = 0;
      break;
    }
  }

  // 再处理其他章节
  if (remaining > 0) {
    for (const section of otherSections) {
      const sectionText = section.fullText;
      if (sectionText.length <= remaining) {
        result.push(sectionText);
        remaining -= sectionText.length;
      } else if (remaining > 100) {
        const truncated = sectionText.slice(0, remaining - 50);
        result.push(truncated + '\n[...内容已精简]');
        remaining = 0;
        break;
      }
    }
  }

  return result.join('\n\n');
}

interface Section {
  title: string;
  content: string;
  fullText: string;
}

/**
 * 按章节分割文本
 */
function splitBySections(text: string): Section[] {
  const lines = text.split('\n');
  const sections: Section[] = [];
  let currentTitle = '未分类';
  let currentLines: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    
    // 检查是否是章节标题
    let isSection = false;
    for (const header of SECTION_HEADERS) {
      if (trimmed === `## ${header}` || trimmed === header) {
        // 保存之前的章节
        if (currentLines.length > 0) {
          sections.push({
            title: currentTitle,
            content: currentLines.join('\n'),
            fullText: `## ${currentTitle}\n${currentLines.join('\n')}`,
          });
        }
        currentTitle = header;
        currentLines = [];
        isSection = true;
        break;
      }
    }

    if (!isSection) {
      currentLines.push(line);
    }
  }

  // 保存最后一个章节
  if (currentLines.length > 0) {
    sections.push({
      title: currentTitle,
      content: currentLines.join('\n'),
      fullText: currentTitle === '未分类' 
        ? currentLines.join('\n')
        : `## ${currentTitle}\n${currentLines.join('\n')}`,
    });
  }

  return sections;
}

/**
 * 截断过长文本（简单截断，用于非简历内容）
 */
export function truncateText(text: string, maxLength: number = 8000): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength) + '\n\n[...内容已截断]';
}
